/**
 * Sitemap generation (Task 55/57; architecture §7 "Per-language sitemaps
 * with `lastmod`... regenerated by `jobs`"). `jobs/regen-sitemaps.ts` runs
 * `regenerateSitemaps` hourly.
 *
 * FULL COVERAGE (Task 57): every ward's `/ward/{id}` and every candidate's
 * `/candidate/{slug}`, EN and KN, alongside the fixed STATIC_ROUTES set —
 * with real `lastmod` values derived from publish timestamps, never a
 * fabricated `now()` for a dynamic entity (see the per-entity derivation
 * below).
 *
 * HREFLANG ALTERNATES: every `<url>` entry in both language sitemaps
 * carries the same `en`/`kn`/`x-default` `<xhtml:link rel="alternate">`
 * triple that Base.astro emits in `<head>` for the equivalent page — so a
 * crawler reading either language's sitemap learns about both URLs for
 * that resource.
 *
 * LASTMOD DERIVATION:
 *   - Candidate `/candidate/{slug}`: MAX(`candidate_fields.updated_at`)
 *     across that candidate's fields, falling back to `candidates.updated_at`
 *     when it has no fields row yet (one grouped query — see
 *     `candidateRows` below).
 *   - Ward `/ward/{id}`: MAX of the (already-resolved) lastmod of every
 *     candidate in that ward — `ward_issues` carries no `updated_at`
 *     column and `wards` itself carries no timestamp column at all, so a
 *     ward with zero candidates gets NO `<lastmod>` tag rather than a
 *     fabricated `now()`.
 *   - STATIC_ROUTES: the regeneration timestamp, same as before — this is
 *     a small, fixed set of static pages, so "the last time the job ran"
 *     is an acceptable, honest signal for them.
 *
 * CANDIDATE VISIBILITY RULE: every row in `candidates` is included,
 * regardless of `status` — src/pages/candidate/[slug].astro's existence
 * check (and Candidate.astro's own docstring) confirm an UNKNOWN slug is
 * the only thing that 404s; an existing candidate (filed/contesting/
 * withdrawn/rejected/pre-notification) is ALWAYS 200 (PRD §5.2: withdrawn/
 * rejected candidates keep their already-shared URL live behind a neutral
 * notice banner). So there is no "non-renderable" candidate row to filter
 * out here.
 *
 * EXCLUDED (matches architecture §7/§8's "noindex and sitemap exclusion"
 * list verbatim): `/partner/{slug}` (unlisted), `/account/*`, `/curator/*`,
 * `/admin/*`, `/login`, `/api/*`. None of these are ever enumerated here —
 * STATIC_ROUTES is a fixed public allowlist, and the ward/candidate
 * queries only ever produce `/ward/{id}` and `/candidate/{slug}` paths.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { eq, max } from 'drizzle-orm';
import { localePath, type Lang } from '../../i18n';
import { db } from '../../db/client';
import { candidates, candidateFields, wards } from '../../db/schema';

/**
 * Root-relative, EN-canonical paths — same convention as Base.astro's
 * `path` prop (never `/kn`-prefixed; `localePath` derives the KN twin).
 * Every one of these is a real static top-level page with a KN twin under
 * src/pages/kn/ as of Task 55.
 */
export const STATIC_ROUTES: string[] = [
  '/',
  '/about',
  '/about-election',
  '/check-registration',
  '/data',
  '/partner-with-us',
  '/press',
  '/privacy',
  '/terms',
  '/voting-guide',
  '/voting-guide/how-to-vote',
  '/voting-guide/voter-id',
  '/voting-guide/find-booth',
];

/** Same fallback convention as astro.config.mjs / src/lib/send/calendar.ts. */
const SITE_ORIGIN = process.env.SITE_ORIGIN ?? 'https://bengaluruvotes.opencity.in';

/** A single sitemap entry: an EN-canonical root-relative path plus an optional ISO 8601 `lastmod`. */
interface RouteEntry {
  path: string;
  lastmod?: string;
}

/** Minimal defensive XML-escaping for text interpolated into the sitemap — `loc`/`href` values here are always `URL#href` output (already percent-encoded), so this is belt-and-braces, not load-bearing. */
function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildUrlSet(lang: Lang, entries: RouteEntry[]): string {
  const urls = entries
    .map((entry) => {
      const loc = new URL(localePath(lang, entry.path), SITE_ORIGIN).href;
      const enHref = new URL(localePath('en', entry.path), SITE_ORIGIN).href;
      const knHref = new URL(localePath('kn', entry.path), SITE_ORIGIN).href;
      const lastmodTag = entry.lastmod ? `\n    <lastmod>${entry.lastmod}</lastmod>` : '';
      return (
        `  <url>\n    <loc>${escapeXml(loc)}</loc>${lastmodTag}\n` +
        `    <xhtml:link rel="alternate" hreflang="en" href="${escapeXml(enHref)}"/>\n` +
        `    <xhtml:link rel="alternate" hreflang="kn" href="${escapeXml(knHref)}"/>\n` +
        `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(enHref)}"/>\n` +
        `  </url>`
      );
    })
    .join('\n');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n` +
    `${urls}\n</urlset>\n`
  );
}

function buildSitemapIndex(lastmod: string): string {
  const enLoc = new URL('/sitemap-en.xml', SITE_ORIGIN).href;
  const knLoc = new URL('/sitemap-kn.xml', SITE_ORIGIN).href;
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `  <sitemap>\n    <loc>${enLoc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>\n` +
    `  <sitemap>\n    <loc>${knLoc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>\n` +
    `</sitemapindex>\n`
  );
}

export interface RegenerateSitemapsResult {
  outputDir: string;
  routesPerLanguage: number;
  files: string[];
}

/**
 * Writes `sitemap-en.xml`, `sitemap-kn.xml`, and a `sitemap.xml` index into
 * `outputDir`, which defaults to the repo's `public/` directory — the same
 * directory Astro's own static assets are served from, so these land
 * wherever the running deployment already serves `/robots.txt`-adjacent
 * static files from. Tests pass a temp directory so runs never dirty the
 * working tree.
 */
export async function regenerateSitemaps(
  outputDir: string = path.join(process.cwd(), 'public'),
): Promise<RegenerateSitemapsResult> {
  mkdirSync(outputDir, { recursive: true });

  const regenTimestamp = new Date().toISOString();

  const wardRows = await db.select({ id: wards.id }).from(wards);

  // One grouped query: every candidate row (ANY status — see the module
  // docstring's visibility rule) alongside the MAX updated_at across its
  // candidate_fields rows. Grouping by candidates.id alone is enough for
  // Postgres to permit selecting the other candidates columns too (they're
  // functionally dependent on the primary key).
  const candidateRows = await db
    .select({
      slug: candidates.slug,
      wardId: candidates.wardId,
      candidateUpdatedAt: candidates.updatedAt,
      maxFieldUpdatedAt: max(candidateFields.updatedAt),
    })
    .from(candidates)
    .leftJoin(candidateFields, eq(candidateFields.candidateId, candidates.id))
    .groupBy(candidates.id);

  const candidateEntries: RouteEntry[] = [];
  const wardLastmodByWardId = new Map<number, Date>();

  for (const row of candidateRows) {
    const lastmodDate = row.maxFieldUpdatedAt ?? row.candidateUpdatedAt;
    candidateEntries.push({ path: `/candidate/${row.slug}`, lastmod: lastmodDate.toISOString() });

    const currentWardMax = wardLastmodByWardId.get(row.wardId);
    if (!currentWardMax || lastmodDate > currentWardMax) {
      wardLastmodByWardId.set(row.wardId, lastmodDate);
    }
  }

  const wardEntries: RouteEntry[] = wardRows.map((ward) => {
    const lastmodDate = wardLastmodByWardId.get(ward.id);
    return { path: `/ward/${ward.id}`, lastmod: lastmodDate?.toISOString() };
  });

  const staticEntries: RouteEntry[] = STATIC_ROUTES.map((route) => ({ path: route, lastmod: regenTimestamp }));

  const allEntries = [...staticEntries, ...wardEntries, ...candidateEntries];

  writeFileSync(path.join(outputDir, 'sitemap-en.xml'), buildUrlSet('en', allEntries), 'utf-8');
  writeFileSync(path.join(outputDir, 'sitemap-kn.xml'), buildUrlSet('kn', allEntries), 'utf-8');
  writeFileSync(path.join(outputDir, 'sitemap.xml'), buildSitemapIndex(regenTimestamp), 'utf-8');

  return {
    outputDir,
    routesPerLanguage: allEntries.length,
    files: ['sitemap.xml', 'sitemap-en.xml', 'sitemap-kn.xml'],
  };
}
