import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { writeFileSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { getPageContent } from '../../src/i18n/content';

const ALL_SLUGS = [
  'about',
  'about-election',
  'check-registration',
  'voting-guide',
  'voter-id',
  'how-to-vote',
  'find-booth',
  'terms',
  'privacy',
  'donate',
  'partner-with-us',
  'press',
  'home-intro',
];

describe('getPageContent()', () => {
  it('returns an entry with a non-empty title for a known EN slug', () => {
    const entry = getPageContent('en', 'about');
    expect(entry).not.toBeNull();
    expect(entry?.title).toBeTruthy();
    expect(typeof entry?.title).toBe('string');
  });

  it('resolves all 13 EN slugs', () => {
    for (const slug of ALL_SLUGS) {
      const entry = getPageContent('en', slug);
      expect(entry, `expected an EN entry for slug "${slug}"`).not.toBeNull();
      expect(entry?.title).toBeTruthy();
      expect(entry?.description).toBeTruthy();
      expect(entry?.body.length ?? 0).toBeGreaterThan(0);
    }
  });

  it('resolves a genuine KN entry now that Task 9 has generated content/pages/kn/*.md', () => {
    const en = getPageContent('en', 'about');
    const kn = getPageContent('kn', 'about');
    expect(kn).not.toBeNull();
    expect(kn?.lang).toBe('kn');
    expect(kn?.fallback).toBe(false);
    expect(kn?.title).toBeTruthy();
    // The KN title is a genuine translation, not a copy of the EN title.
    expect(kn?.title).not.toBe(en?.title);
  });

  it('resolves all 13 KN slugs generated by Task 9, none as a fallback', () => {
    for (const slug of ALL_SLUGS) {
      const entry = getPageContent('kn', slug);
      expect(entry, `expected a KN entry for slug "${slug}"`).not.toBeNull();
      expect(entry?.lang, `slug "${slug}"`).toBe('kn');
      expect(entry?.fallback, `slug "${slug}"`).toBe(false);
      expect(entry?.title).toBeTruthy();
      expect(entry?.description).toBeTruthy();
      expect(entry?.body.length ?? 0).toBeGreaterThan(0);
    }
  });

  it('returns null for an unknown slug', () => {
    expect(getPageContent('en', 'no-such-page')).toBeNull();
    expect(getPageContent('kn', 'no-such-page')).toBeNull();
  });

  it('marks a genuine EN entry as not a fallback', () => {
    const entry = getPageContent('en', 'about');
    expect(entry?.fallback).toBe(false);
  });

  describe('KN-missing → EN-fallback path', () => {
    const testFixtureName = '__test-fixture-fallback';
    const testFixtureFile = path.join(
      new URL('../../content/pages/en/', import.meta.url).pathname,
      `${testFixtureName}.md`,
    );

    beforeAll(() => {
      // Create a temporary EN fixture file. Since KN version won't exist, this
      // tests the fallback→EN path. The `__test-fixture-fallback` name cannot
      // collide with real slugs (which are alphanumeric/hyphens, not starting
      // with `__`), and cleanup below ensures it doesn't persist or trigger
      // staleness warnings.
      const frontmatter = `---
title: Test Fixture Fallback
description: A temporary fixture for testing EN fallback when KN is missing
---`;
      const body = '\n# Test Content\n\nThis is a test fixture.';
      writeFileSync(testFixtureFile, `${frontmatter}${body}`, 'utf-8');
    });

    afterAll(() => {
      // Clean up the fixture unconditionally, even if tests fail.
      try {
        unlinkSync(testFixtureFile);
      } catch {
        // File may have already been deleted or not exist.
      }
    });

    it('returns EN entry with fallback=true when KN file is missing', () => {
      const knEntry = getPageContent('kn', testFixtureName);
      expect(knEntry).not.toBeNull();
      expect(knEntry?.lang).toBe('en');
      expect(knEntry?.fallback).toBe(true);
      expect(knEntry?.title).toBe('Test Fixture Fallback');
    });

    it('marks genuine EN entry (direct request) as not a fallback', () => {
      const enEntry = getPageContent('en', testFixtureName);
      expect(enEntry).not.toBeNull();
      expect(enEntry?.fallback).toBe(false);
      expect(enEntry?.lang).toBe('en');
    });
  });
});
